<?php
/**
 * New Customer block template
 * @var $block \Magento\Customer\Block\Form\Login\Info
 */
?>
<?php if ($block->getRegistration()->isAllowed()): ?>
<div class="block block-new-customer">
  <div class="block-title">
    <strong id="block-new-customer-heading"
            role="heading"
            aria-level="2"><?php echo __('Sign Me Up!') ?></strong>
  </div>
  <div class="block-content" aria-labelledby="block-new-customer-heading">
    <div class="actions-toolbar">
      <div class="primary">
        <a href="<?php echo $block->getCreateAccountUrl() ?>"
           class="action create primary">
          <span><?php echo __('I WANT ONE!') ?></span>
        </a>
      </div>
    </div>
  </div>
</div>
<?php endif; ?>
